@startuml mainLogic
start
:Init variables;

:Print menu;

repeat

:input action;

switch(Action)
case (fight)
    :took randomDamage;
    :got random damage;

case (act)
    :you complement
    It seems flattered;
    :DummyHappy=DummyHappy - 1;
    :you got random damage;

case (item)

    switch(CHOOSE ITEM)
        case (monster candy +5 hp)
            if (ItemMC>0) THEN (true)
                :Health + 5;
                :ItemMC=ItemMC-1;
            ELSE
                :you ran out of this item;
            endif

        case (sea tea(+9 hp))
            if (ItemST>0) THEN (true)
                :Health + 5;
                :ItemST=ItemST-1;
            ELSE
                :you ran out of this item;
            endif

        case (Butterscotch-Cinnamon Pie+19 hp)
            if (ItemBCP>0) THEN (true)
                :Health + 5;
                :ItemBCP=ItemBCP-1;
            ELSE
                :you ran out of this item;
            endif
        case (else)
            :you dont have this item...;
    endswitch

case (mercy)
    if (DummySpare>0) then (true)
        :DummyName$ is too angry to be spared;
        :You got random damage;
    endif

    if (DummySpare=0) then (true)
        :got XP;
        :Got gold;
        :you won!;
        stop
    endif

endswitch

if (YourHealth <= 0) then (true)
    stop
endif

if (DummyHappy = 0) then (true)
    :PRINT DummyName$; "is smiling";
    :DummySpare=DummySpare=-1;
endif

if (DummyHealth <= 0) then (true)
    :Got XP;
    :Got gold;
    :You win;
    stop
endif

repeat while (true)

@enduml