@startuml mainLogic
start
:Init variables
strangerDiscovered=0
castleDiscovered=0
gameFinish=0;

repeat

    :generateActionsMenu;

    :input actionChoice;

    switch(actionChoice)
        case (1)
            :PRINT "You walked around a bit.";

        case (2)
            :call SHOP;

        case (3)
            :call MyInfo;

        CASE (4)
            if (seeDummy=1) then
                :call BATTLE;
            endif
        case (5)
            if (seeBushes = 1) then
                :call SEARCHINBUSHES;
            endif
        case (6)
            if (castleDiscovered = 1) then
                :call CASTLE;
            endif
        case (7)
            if (strangerDiscovered = 1) then
                :call STRANGER;
            endif

        case (else)
            :PRINT "You walked around a bit.";

    endswitch

if (gameFinish=1) then
    stop
endif

if (PlayerCurrentHealth <= 0) then
    stop
endif

repeat while (true)

@enduml
